INSERT INTO menus (label, icon, parent_id) VALUES ('Home', 'pi pi-home', NULL);
INSERT INTO menus (label, icon, parent_id) VALUES ('Features', 'pi pi-star', NULL);
INSERT INTO menus (label, icon, parent_id) VALUES ('Projects', 'pi pi-search', NULL);
INSERT INTO menus (label, icon, parent_id) VALUES ('Components', 'pi pi-bolt', 3);
INSERT INTO menus (label, icon, parent_id) VALUES ('Blocks', 'pi pi-server', 3);
INSERT INTO menus (label, icon, parent_id) VALUES ('UI Kit', 'pi pi-pencil', 3);
INSERT INTO menus (label, icon, parent_id) VALUES ('Templates', 'pi pi-palette', 3);
INSERT INTO menus (label, icon, parent_id) VALUES ('Apollo', 'pi pi-palette', 7);
INSERT INTO menus (label, icon, parent_id) VALUES ('Ultima', 'pi pi-palette', 7);
INSERT INTO menus (label, icon, parent_id) VALUES ('Contact', 'pi pi-envelope', NULL);
